ticksUntilDeath = 2400
continueTimerWhileOffline = true
rescueActionTicks = 40
rescueRespawnHealth = 6
rescueRespawnFoodLevel = 10
rescueRespawnEffects = ["minecraft:hunger|600|0", "minecraft:weakness|1200|0"]
rescueDistance = 5.0
glowOnKnockout = true
allowUnarmedMelee = false
allowBows = false
allowPistols = false
