# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = [
    "Empty or non-existent pool:",
    "Error during settings get:",
    "Starting initial dragon fight!",
    "Invalid mod icon for icon source",
    "UUID of added entity already exists",
    "Hanging entity at invalid position",
    "Error getting user info for",
    "Error checking for cosmetic updates on the remote server",
    "This makes sure Expanded Delight mixins are loaded",
    "This line is printed by an example mod mixin!",
    "Disconnecting VANILLA connection attempt"
]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = [
    "/^Reclaimed .+ bytes at address .+ that were leaked$/"
    "/^Error from mod '.+'$/"
    "/^Couldn't load tag .+ as it is missing following references$/",
    "/^Changing .+ distance to$/"
]