fallDamageReduction = 0.5
fallDamageThreshold = 20
speedReductionHorizontal = 0.6
speedReductionVertical = 0.8
modifyPathFinding = true
playerOnly = false

[modules]
enchantment = true

[sounds]
volume = 1.0
playerOnly = false
