name = "Minecraft Two"
author = "ItsMeTrevor"
version = "4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1762c844a556e3cde827cac4d295100dc6ab1b068594ea5dd20cb076969d0d07"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
