version: '3.8'

services:
  minecrafttwo:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data:rw
    ports:
      - "25565:25565"
      - "24454:24454"
    environment:
      EULA: "true"
      TYPE: FABRIC
      DEBUG: true
      VERSION: 1.19.2
      FABRIC_LAUNCHER_VERSION: 0.11.2
      FABRIC_LOADER_VERSION: 0.14.22
      INIT_MEMORY: 256M
      MAX_MEMORY: 14G
